name: Build and Deploy
on:
  push:
    branches:
      master
jobs:
  # 任务ID
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    # 步骤
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: run deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: npm install && npm run deploy

